const menu = [
  {
    id: 1,
    title: 'Panquecas de manteiga',
    category: 'café da manhã',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: 'Panquecas com manteiga, servidas com xarope de bordo e acompanhamentos',
  },
  {
    id: 2,
    title: 'Hambúrguer duplo',
    category: 'almoço',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: 'Dois hambúrgueres suculentos com queijo americano, alface, tomate e cebola roxa em um pão macio de brioche',
  },
  {
    id: 3,
    title: 'Milkshake Godzilla',
    category: 'bebidas',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: 'Milkshake de baunilha com pedaços de bolo de chocolate, chantilly e uma cereja no topo',
  },
  {
    id: 4,
    title: 'Delícia do campo',
    category: 'café da manhã',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: 'Ovos mexidos, bacon crocante, torradas de pão integral e batata rústica assada com ervas',
  },
  {
    id: 5,
    title: 'Ataque de ovos',
    category: 'almoço',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: 'Sanduíche de pão de centeio com ovo frito, queijo suíço, bacon e maionese caseira',
  },
  {
    id: 6,
    title: 'Sonho de Oreo',
    category: 'bebidas',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: 'Milkshake de baunilha com biscoitos Oreo triturados e chantilly',
  },
  {
    id: 7,
    title: 'Overflow de bacon',
    category: 'café da manhã',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: 'Ovos mexidos cremosos com bacon crocante e torradas de pão de forma',
  },
  {
    id: 8,
    title: 'Clássico americano',
    category: 'almoço',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: 'Sanduíche de frango frito com queijo cheddar, alface e molho especial em um pão de brioche',
  },
  {
    id: 9,
    title: 'Companheiro de quarentena',
    category: 'teste de categoria',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: 'Prato de macarrão com queijo, servido com pão de alho e legumes grelhados',
  },
];

export default menu;